name: diplom
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  # state management
  stacked: ^2.2.8

  # navigation
  auto_route: ^3.2.2

  # dependencies
  provider: ^6.0.2
  get_it: ^7.2.0

  # local storage
  hive: ^2.0.5
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9

  # images
  cached_network_image: ^3.2.0

  # firebase
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_storage: ^10.2.7
  cloud_firestore: ^3.1.8
  firebase_database: ^9.0.8

  #sign in providers
  sign_in_with_apple: ^3.3.0
  google_sign_in: ^5.2.3

  # widgets
  google_fonts: ^2.3.1
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.8
  flutter_slidable: ^1.2.0
  auto_size_text: ^3.0.0
  auto_size_text_field: ^1.0.1

  # services
  flutter_keyboard_visibility: ^5.1.1
  connectivity_plus: ^2.2.0

  # other
  url_launcher: ^6.0.20
  intl: ^0.17.0
  uuid: ^3.0.5
  logger: ^1.1.0
  email_validator: ^2.0.1
  package_info_plus: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

  # code generation
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
    - assets/logos/

