name: diplom
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # state management
  stacked: ^2.2.7+1

  # navigation
  auto_route: ^3.2.1

  # dependencies
  provider: ^6.0.2
  get_it: ^7.2.0

  # local storage
  hive: ^2.0.5
  shared_preferences: ^2.0.12
  path_provider: ^2.0.8

  # images
  cached_network_image: ^3.2.0

  # firebase
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  cloud_firestore: ^3.1.6

  # widgets
  fluttertoast: ^8.0.8
  flutter_slidable: ^1.2.0

  # other
  url_launcher: ^6.0.18
  google_fonts: ^2.2.0
  intl: ^0.17.0
  uuid: ^3.0.5
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # code generation
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png

